version: "3.9"
services:
    db:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            # These password and stuff is not neccesarry too secret
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: todoapp
            # - MYSQL_PASSWORD=db_password
            MYSQL_DATABASE: todolist
            MYSQL_PASSWORD: 123456

    todoapp:
        build: ./todoapp
        restart: unless-stopped
        ports:
            - 24001:80
        volumes:
            - ./todoapp/src:/var/www/html
        depends_on:
      # Ensure MySQL is started before PHP
            - db
        # environment:
        #     # These password and stuff is not neccesarry too secret
        #     - MYSQL_HOSTNAME=db
        #     - MYSQL_ROOT_PASSWORD=""
        #     - MYSQL_USER=root
        #     # - MYSQL_PASSWORD=db_password
